"use client";
import { useState } from "react";
import useSWR from "swr";
import { fetchEvidence, fetchClaims, fetchKnowledgeGraph, searchKnowledge, fetchSourceReputations, fetchScoreboard } from "@/lib/api";

type Tab = "evidence" | "claims" | "graph" | "reputation" | "calibration";

export default function EvidencePage() {
  const [tab, setTab] = useState<Tab>("evidence");
  const [q, setQ] = useState("");
  const { data: ev } = useSWR(tab === "evidence" ? "ev" : null, () => fetchEvidence(100));
  const { data: cl } = useSWR(tab === "claims" ? "cl" : null, () => fetchClaims(100));
  const { data: graph } = useSWR(tab === "graph" ? "graph" : null, () => fetchKnowledgeGraph(200));
  const { data: rep } = useSWR(tab === "reputation" ? "rep" : null, fetchSourceReputations);
  const { data: sb } = useSWR(tab === "calibration" ? "sb" : null, fetchScoreboard);
  const { data: sr } = useSWR(q.length > 2 ? `sr-${q}` : null, () => searchKnowledge(q), { dedupingInterval: 1000 });
  const TABS: { key: Tab; label: string }[] = [{ key: "evidence", label: "Evidence" }, { key: "claims", label: "Claims" }, { key: "graph", label: "Knowledge Graph" }, { key: "reputation", label: "Source Reputation" }, { key: "calibration", label: "Calibration" }];

  return (
    <div className="space-y-4">
      <h1 className="text-lg font-bold">Intelligence Center</h1>
      <div className="flex gap-1">{TABS.map((t) => <button key={t.key} onClick={() => setTab(t.key)} className={`text-xs px-3 py-1.5 rounded ${tab === t.key ? "bg-[var(--accent)] text-white" : "bg-[var(--card)] text-[var(--muted)]"}`}>{t.label}</button>)}</div>
      {tab === "evidence" && <div className="bg-[var(--card)] border border-[var(--card-border)] rounded-lg"><table className="w-full text-xs"><thead><tr className="text-[var(--muted)] border-b border-[var(--card-border)]"><th className="text-left p-3">Title</th><th className="text-left p-3">Summary</th><th className="text-right p-3">Confidence</th></tr></thead><tbody>{ev?.map((e) => <tr key={e.id} className="border-b border-[var(--card-border)] last:border-0 hover:bg-[var(--background)]"><td className="p-3 max-w-xs truncate">{e.title}</td><td className="p-3 text-[var(--muted)] max-w-md truncate">{e.summary}</td><td className="p-3 text-right"><span className={e.confidence >= 0.7 ? "text-[var(--accent-green)]" : e.confidence >= 0.4 ? "text-[var(--accent-yellow)]" : "text-[var(--accent-red)]"}>{(e.confidence * 100).toFixed(0)}%</span></td></tr>)}</tbody></table>{(!ev || !ev.length) && <div className="text-sm text-[var(--muted)] text-center py-8">No evidence</div>}</div>}
      {tab === "claims" && <div className="bg-[var(--card)] border border-[var(--card-border)] rounded-lg"><table className="w-full text-xs"><thead><tr className="text-[var(--muted)] border-b border-[var(--card-border)]"><th className="text-left p-3">Statement</th><th className="text-right p-3">Confidence</th><th className="text-right p-3">Status</th></tr></thead><tbody>{cl?.map((c) => <tr key={c.id} className="border-b border-[var(--card-border)] last:border-0 hover:bg-[var(--background)]"><td className="p-3 max-w-xl truncate">{c.statement}</td><td className="p-3 text-right">{(c.confidence * 100).toFixed(0)}%</td><td className="p-3 text-right"><span className={`px-2 py-0.5 rounded ${c.status === "ACCEPTED" ? "bg-[var(--accent-green)]/20 text-[var(--accent-green)]" : c.status === "REJECTED" ? "bg-[var(--accent-red)]/20 text-[var(--accent-red)]" : "bg-[var(--accent-yellow)]/20 text-[var(--accent-yellow)]"}`}>{c.status}</span></td></tr>)}</tbody></table>{(!cl || !cl.length) && <div className="text-sm text-[var(--muted)] text-center py-8">No claims</div>}</div>}
      {tab === "graph" && <div className="space-y-4"><div className="flex gap-2"><input className="flex-1 bg-[var(--card)] border border-[var(--card-border)] rounded p-2 text-sm" placeholder="Search knowledge graph..." value={q} onChange={(e) => setQ(e.target.value)} /></div>{sr && sr.length > 0 && <div className="bg-[var(--card)] border border-[var(--card-border)] rounded-lg p-4"><h3 className="text-sm font-semibold mb-2">Results</h3>{sr.map((r) => <div key={r.node_id} className="text-xs py-1.5 flex justify-between border-b border-[var(--card-border)] last:border-0"><span>{r.label}</span><span className="text-[var(--accent)]">{(r.score * 100).toFixed(0)}%</span></div>)}</div>}{graph && <div className="bg-[var(--card)] border border-[var(--card-border)] rounded-lg p-4"><h3 className="text-sm font-semibold mb-2">{graph.nodes.length} nodes, {graph.edges.length} edges</h3><div className="grid grid-cols-2 md:grid-cols-4 gap-2 max-h-96 overflow-y-auto">{graph.nodes.slice(0, 80).map((n) => <div key={n.node_id} className="text-xs p-2 rounded bg-[var(--background)] border border-[var(--card-border)]"><div className="font-medium truncate">{n.label}</div><div className="text-[var(--muted)]">{n.node_type}</div></div>)}</div></div>}</div>}
      {tab === "reputation" && <div className="bg-[var(--card)] border border-[var(--card-border)] rounded-lg"><table className="w-full text-xs"><thead><tr className="text-[var(--muted)] border-b border-[var(--card-border)]"><th className="text-left p-3">Source</th><th className="text-left p-3">Type</th><th className="text-right p-3">Reputation</th><th className="text-right p-3">Confirmed</th><th className="text-right p-3">Refuted</th></tr></thead><tbody>{rep?.sort((a, b) => b.reputation_score - a.reputation_score).map((r, i) => <tr key={i} className="border-b border-[var(--card-border)] last:border-0 hover:bg-[var(--background)]"><td className="p-3">{r.display_name || r.source_key}</td><td className="p-3 text-[var(--muted)]">{r.source_type || "—"}</td><td className="p-3 text-right"><span className={r.reputation_score >= 0.6 ? "text-[var(--accent-green)]" : "text-[var(--accent-yellow)]"}>{r.reputation_score.toFixed(3)}</span></td><td className="p-3 text-right text-[var(--accent-green)]">{r.confirmed_count}</td><td className="p-3 text-right text-[var(--accent-red)]">{r.refuted_count}</td></tr>)}</tbody></table>{(!rep || !rep.length) && <div className="text-sm text-[var(--muted)] text-center py-8">No data</div>}</div>}
      {tab === "calibration" && <div className="bg-[var(--card)] border border-[var(--card-border)] rounded-lg p-4">{sb ? <div className="space-y-4"><div className="grid grid-cols-4 gap-4 text-center"><div><div className="text-2xl font-bold">{sb.total_hypotheses}</div><div className="text-xs text-[var(--muted)]">Total</div></div><div><div className="text-2xl font-bold text-[var(--accent-green)]">{(sb.accuracy * 100).toFixed(0)}%</div><div className="text-xs text-[var(--muted)]">Accuracy</div></div><div><div className="text-2xl font-bold">{sb.brier_score?.toFixed(3) ?? "—"}</div><div className="text-xs text-[var(--muted)]">Brier</div></div><div><div className="text-2xl font-bold text-[var(--accent)]">{sb.human_baseline_accuracy != null ? `${((sb.lift_over_human_baseline ?? 0) * 100).toFixed(1)}%` : "—"}</div><div className="text-xs text-[var(--muted)]">vs Human</div></div></div><div className="grid grid-cols-3 gap-4 text-center"><div className="p-3 rounded bg-[var(--accent-green)]/10"><div className="text-lg font-bold text-[var(--accent-green)]">{sb.confirmed}</div><div className="text-xs text-[var(--muted)]">Confirmed</div></div><div className="p-3 rounded bg-[var(--accent-red)]/10"><div className="text-lg font-bold text-[var(--accent-red)]">{sb.refuted}</div><div className="text-xs text-[var(--muted)]">Refuted</div></div><div className="p-3 rounded bg-[var(--accent-yellow)]/10"><div className="text-lg font-bold text-[var(--accent-yellow)]">{sb.pending}</div><div className="text-xs text-[var(--muted)]">Pending</div></div></div></div> : <div className="text-sm text-[var(--muted)] text-center py-8">Loading...</div>}</div>}
    </div>
  );
}
