from __future__ import annotations

import re

_TOKEN_RE = re.compile(r"[a-z0-9]+")
_CLAIM_STOPWORDS = {
    "the",
    "and",
    "for",
    "with",
    "this",
    "that",
    "from",
    "after",
    "before",
    "into",
    "across",
    "over",
    "under",
    "still",
    "remain",
    "remained",
    "during",
    "through",
    "their",
    "there",
    "about",
}
_POSITIVE_CLAIM_KEYWORDS = {
    "increase",
    "increased",
    "improve",
    "improved",
    "grow",
    "grew",
    "growing",
    "gain",
    "gained",
    "ship",
    "shipped",
    "launch",
    "launched",
    "deploy",
    "deployed",
    "restore",
    "restored",
    "rise",
    "rose",
    "support",
    "supported",
    "open",
    "opened",
}
_NEGATIVE_CLAIM_KEYWORDS = {
    "decrease",
    "decreased",
    "decline",
    "declined",
    "drop",
    "dropped",
    "fall",
    "fell",
    "delay",
    "delayed",
    "cancel",
    "canceled",
    "block",
    "blocked",
    "disrupt",
    "disrupted",
    "reduce",
    "reduced",
    "damage",
    "damaged",
    "loss",
    "losses",
    "reject",
    "rejected",
    "withdraw",
    "withdrew",
}
_BIAS_PATTERNS: dict[str, list[str]] = {
    "confirmation_bias": [
        "confirms",
        "as expected",
        "proves",
        "clearly shows",
        "undeniable",
        "without doubt",
        "obvious that",
        "always leads to",
        "inevitably",
    ],
    "cherry_picking": [
        "for example",
        "one case where",
        "specific instance of",
        "in one study",
        "a single case",
        "ignore the rest",
        "only evidence that",
        "selectively citing",
        "hand-picked",
    ],
    "hand_waving": [
        "roughly",
        "approximately",
        "about",
        "more or less",
        "in the ballpark",
        "general sense",
        "broadly speaking",
        "in theory",
        "should be fine",
    ],
    "excessive_pessimism": [
        "catastrophic",
        "disaster",
        "collapse",
        "unrecoverable",
        "fatal",
        "doomed",
        "point of no return",
        "irreversible damage",
        "total failure",
    ],
}
_RISK_DIMENSIONS = {
    "financial": {
        "budget",
        "cost",
        "revenue",
        "margin",
        "runway",
        "cash",
        "funding",
        "profit",
        "loss",
        "spend",
        "expense",
    },
    "operational": {
        "delivery",
        "velocity",
        "pipeline",
        "throughput",
        "capacity",
        "load",
        "efficiency",
        "bottleneck",
        "latency",
    },
    "strategic": {
        "market",
        "share",
        "competition",
        "positioning",
        "growth",
        "expansion",
        "pivot",
        "acquisition",
    },
    "technical": {
        "reliability",
        "debt",
        "infrastructure",
        "architecture",
        "scalability",
        "security",
        "vulnerability",
        "outage",
    },
    "human_capital": {
        "retention",
        "churn",
        "attrition",
        "hiring",
        "morale",
        "burnout",
        "talent",
        "skill",
    },
    "geopolitical": {
        "sanctions",
        "alliance",
        "treaty",
        "sovereignty",
        "territory",
        "escalation",
        "deterrence",
        "nuclear",
    },
    "logistics": {
        "supply",
        "logistics",
        "transport",
        "inventory",
        "stockpile",
        "distribution",
        "procurement",
    },
    "intelligence": {
        "isr",
        "surveillance",
        "reconnaissance",
        "intelligence",
        "sigint",
        "osint",
        "indicator",
    },
    "civilian_impact": {
        "civilian",
        "humanitarian",
        "refugee",
        "collateral",
        "population",
        "displacement",
    },
    "environmental": {
        "climate",
        "environment",
        "pollution",
        "sustainability",
        "carbon",
        "emission",
    },
}
